CREATE OR ALTER PROCEDURE SITE_GET_GROUP_EMPLOYEES
RETURNS (
    ID bigint
    ,NAME varchar(500)
)
AS
BEGIN
FOR
    SELECT
        DISTINCT V269.LISTVAL_ID
        ,RV269.VAL
    FROM
        VALL V269
        JOIN LISTVALS LV269 ON LV269.LISTVAL_ID = V269.LISTVAL_ID
        LEFT JOIN RES_GET(LV269.RES_ID, 'RU') RV269 ON 1 = 1
    WHERE
        V269.PARAM_ID = 269
    INTO
        ID
        ,NAME
    DO BEGIN
        SUSPEND;
    END
END